services:

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data

  backend:
    build:
      .
    depends_on:
      - database
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
